{
  "patch_root_path": "https://raw.githubusercontent.com/cloudify-cosmo/patchify/master/patch_files/", 
  "patches": [
    {
      "patch_definition_path": "46_local_tasks_restore.json", 
      "patch_description": "Dump/restore support for local tasks.", 
      "patch_files": [
        "46_local_tasks_restore_cloudify_workflows_tasks.py", 
        "46_local_tasks_restore_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_id": "46_local_tasks_restore-316b313c3bc441abec887e1e0233223c1d0f2021a973a7c5ed2f700dce2ddd42", 
      "patch_name": "46_local_tasks_restore", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_cfy_status.json", 
      "patch_description": "Allow 'cfy status' command to work even when no Cloudify license is uploaded to the Manager.", 
      "patch_files": [
        "4_6_fix_cfy_status_rest-service_manager_rest_constants.py"
      ], 
      "patch_hash": "07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_id": "4_6_fix_cfy_status-07606535edb47639e39dbc9dfe22778127de40eb7d9fbfd075c03e22bc548ea2", 
      "patch_name": "4_6_fix_cfy_status", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_hooks_with_plugins.json", 
      "patch_description": "Fix for actionable events (hooks) with plugin implementation.", 
      "patch_files": [
        "4_6_fix_hooks_with_plugins_cloudify_agent_worker.py", 
        "4_6_fix_hooks_with_plugins_cloudify_dispatch.py", 
        "4_6_fix_hooks_with_plugins_cloudify_logs.py"
      ], 
      "patch_hash": "dfe41214d8d5968ce8db07d4f382b7fe84a7222c3c65244e296dc4eb7a7cee5d", 
      "patch_id": "4_6_fix_hooks_with_plugins-dfe41214d8d5968ce8db07d4f382b7fe84a7222c3c65244e296dc4eb7a7cee5d", 
      "patch_name": "4_6_fix_hooks_with_plugins", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_getnodeinstancestate_typo.json", 
      "patch_description": "Fix typo in GetNodeInstanceState task.", 
      "patch_files": [
        "46_getnodeinstancestate_typo_cloudify_workflows_tasks.py"
      ], 
      "patch_hash": "6191046f297c4c0838b7d673064d9f8c5ef7d19fda8c8206c1a97601611bc7e1", 
      "patch_id": "46_getnodeinstancestate_typo-6191046f297c4c0838b7d673064d9f8c5ef7d19fda8c8206c1a97601611bc7e1", 
      "patch_name": "46_getnodeinstancestate_typo", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_improve_failed_snapshot_restore_output.json", 
      "patch_description": "Give more helpful output when a snapshot DB restore fails.", 
      "patch_files": [
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_postgres.py", 
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_snapshot_restore.py", 
        "4_6_improve_failed_snapshot_restore_output_workflows_cloudify_system_workflows_snapshots_utils.py"
      ], 
      "patch_hash": "5e7d774790d66846c19d518445dd038234a87594273e9cb174afc747aa6f826f", 
      "patch_id": "4_6_improve_failed_snapshot_restore_output-5e7d774790d66846c19d518445dd038234a87594273e9cb174afc747aa6f826f", 
      "patch_name": "4_6_improve_failed_snapshot_restore_output", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_refresh_ni_scale.json", 
      "patch_description": "Scale workflow: refresh node instances.", 
      "patch_files": [
        "46_refresh_ni_scale_cloudify_plugins_workflows.py", 
        "46_refresh_ni_scale_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "7216e5739778b8afc9db680f2551ddf77a9d31255ac3da02ac4294d94c410f6e", 
      "patch_id": "46_refresh_ni_scale-7216e5739778b8afc9db680f2551ddf77a9d31255ac3da02ac4294d94c410f6e", 
      "patch_name": "46_refresh_ni_scale", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_handle_null_failed_logins_counter.json", 
      "patch_description": "Allow snapshot restore to work with null failed_logins_counter.", 
      "patch_files": [
        "4_6_handle_null_failed_logins_counter_resources_rest-service_cloudify_migrations_versions_1fbd6bf39e84_4_5_to_4_5_5.py"
      ], 
      "patch_hash": "3945c66e2a40c6308d40d4b44797abb18bc07d433576345e243a33ab5687c848", 
      "patch_id": "4_6_handle_null_failed_logins_counter-3945c66e2a40c6308d40d4b44797abb18bc07d433576345e243a33ab5687c848", 
      "patch_name": "4_6_handle_null_failed_logins_counter", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_update_error_param_workflow_failed_trap.json", 
      "patch_description": "update the error parameter in the workflow_failed snmp trap.", 
      "patch_files": [
        "4_6_update_error_param_workflow_failed_trap_cloudify_snmp_snmp_trap.py"
      ], 
      "patch_hash": "d04c3b8c1390097c8c564f1e5b0fa1ebe418e42c74b1d4da48fe2fddd0c06243", 
      "patch_id": "4_6_update_error_param_workflow_failed_trap-d04c3b8c1390097c8c564f1e5b0fa1ebe418e42c74b1d4da48fe2fddd0c06243", 
      "patch_name": "4_6_update_error_param_workflow_failed_trap", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_reset_operations_retry.json", 
      "patch_description": "Don't run retried tasks twice in resume with reset-operations.", 
      "patch_files": [
        "46_reset_operations_retry_cloudify_workflows_tasks.py", 
        "46_reset_operations_retry_manager_rest-service_manager_rest_resource_manager.py"
      ], 
      "patch_hash": "280b1c5e3173f35e2670979c8f6e4805c0bae41912bf9c46c4208d343b2879a7", 
      "patch_id": "46_reset_operations_retry-280b1c5e3173f35e2670979c8f6e4805c0bae41912bf9c46c4208d343b2879a7", 
      "patch_name": "46_reset_operations_retry", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_resume_cancelled.json", 
      "patch_description": "Allow resuming cancelled workflows.", 
      "patch_files": [
        "46_resume_cancelled_cloudify_workflows_tasks.py", 
        "46_resume_cancelled_cloudify_amqp_client.py", 
        "46_resume_cancelled_cloudify_endpoint.py", 
        "46_resume_cancelled_cloudify_context.py", 
        "46_resume_cancelled_cloudify_dispatch.py", 
        "46_resume_cancelled_cloudify_tests_mocks_mock_rest_client.py", 
        "46_resume_cancelled_cloudify_tests_test_dispatch.py", 
        "46_resume_cancelled_cloudify_workflows_workflow_context.py", 
        "46_resume_cancelled_manager_rest-service_manager_rest_resource_manager.py"
      ], 
      "patch_hash": "b3a9d44a0498bc69e5a465b6e263594804323cc109bb4ebb63c9155b757b2580", 
      "patch_id": "46_resume_cancelled-b3a9d44a0498bc69e5a465b6e263594804323cc109bb4ebb63c9155b757b2580", 
      "patch_name": "46_resume_cancelled", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_store_failed_operations.json", 
      "patch_description": "Correctly store failed operations state.", 
      "patch_files": [
        "46_store_failed_operations_cloudify_dispatch.py"
      ], 
      "patch_hash": "797f2d730bf6dd1c343f3d5b4baa97914aede9ea3bf4103b368ed567312d524c", 
      "patch_id": "46_store_failed_operations-797f2d730bf6dd1c343f3d5b4baa97914aede9ea3bf4103b368ed567312d524c", 
      "patch_name": "46_store_failed_operations", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_authorization_tasksgraph.json", 
      "patch_description": "Add fine-grained access control for tasks graphs and operations.", 
      "patch_files": [
        "46_authorization_add_tasksgraphs"
      ], 
      "patch_hash": "d59f250a0bb6656728a85b2b2a4638a17b2371a0a9a3227cfac87896dc897853", 
      "patch_id": "46_authorization_tasksgraph-d59f250a0bb6656728a85b2b2a4638a17b2371a0a9a3227cfac87896dc897853", 
      "patch_name": "46_authorization_tasksgraph", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_increase_recursion_limit.json", 
      "patch_description": "Recursion limit was increased from 10 to 50 to avoid breaking multi layers blueprints.", 
      "patch_files": [
        "46_increase_recursion_limit_dsl_parser_functions.py"
      ], 
      "patch_hash": "85221417381b5412b460093eb041b89aaa288e7fda59d57553d3fd62411631ea", 
      "patch_id": "46_increase_recursion_limit-85221417381b5412b460093eb041b89aaa288e7fda59d57553d3fd62411631ea", 
      "patch_name": "46_increase_recursion_limit", 
      "supports_community": true
    }, 
    {
      "patch_definition_path": "4_6_use_concat_everywhere.json", 
      "patch_description": "Removing any restriction on concat use.", 
      "patch_files": [
        "4_6_use_concat_everywhere_dsl_parser_functions.py"
      ], 
      "patch_hash": "ed356318d564c394067863fb1a8f8917c00000263d35c69b8716af854b3f304a", 
      "patch_id": "4_6_use_concat_everywhere-ed356318d564c394067863fb1a8f8917c00000263d35c69b8716af854b3f304a", 
      "patch_name": "4_6_use_concat_everywhere", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_do_not_try_to_re_restore_license.json", 
      "patch_description": "Stop failing to restore snapshots that contain licenses.", 
      "patch_files": [
        "4_6_do_not_try_to_re_restore_license_workflows_cloudify_system_workflows_snapshots_snapshot_restore.py"
      ], 
      "patch_hash": "770559bf3068561c57a1a70f3f900948f86057eca09b6df2b2a12af366b7b15e", 
      "patch_id": "4_6_do_not_try_to_re_restore_license-770559bf3068561c57a1a70f3f900948f86057eca09b6df2b2a12af366b7b15e", 
      "patch_name": "4_6_do_not_try_to_re_restore_license", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_hiding_postgres_credentials.json", 
      "patch_description": "Do not show postgres credentials in snapshot restore logs.", 
      "patch_files": [
        "4_6_hiding_postgres_credentials_workflows_cloudify_system_workflows_snapshots_utils.py", 
        "4_6_hiding_postgres_credentials_workflows_cloudify_system_workflows_snapshots_postgres.py", 
        "4_6_hiding_postgres_credentials_workflows_cloudify_system_workflows_snapshots_snapshot_restore.py"
      ], 
      "patch_hash": "db6aef8b8958f2b0ad8d82396dc3f025db49b438d343cfc1a5e95c687e89bd34", 
      "patch_id": "4_6_hiding_postgres_credentials-db6aef8b8958f2b0ad8d82396dc3f025db49b438d343cfc1a5e95c687e89bd34", 
      "patch_name": "4_6_hiding_postgres_credentials", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_reevaluate_ops_inputs_on_update.json", 
      "patch_description": "Reevaluate operation inputs on deployment update.", 
      "patch_files": [
        "46_reevaluate_ops_inputs_on_update_rest-service_manager_rest_deployment_update_handlers.py", 
        "46_reevaluate_ops_inputs_on_update_rest-service_manager_rest_storage_storage_manager.py"
      ], 
      "patch_hash": "e2ba885fe4970eb538b42ba7295024194c5f338b6f7472d00864299d0a2ca170", 
      "patch_id": "46_reevaluate_ops_inputs_on_update-e2ba885fe4970eb538b42ba7295024194c5f338b6f7472d00864299d0a2ca170", 
      "patch_name": "46_reevaluate_ops_inputs_on_update", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_delete_queue.json", 
      "patch_description": "Delete request/response queues from rabbitmq.", 
      "patch_files": [
        "46_delete_queue_cloudify_amqp_client.py", 
        "46_delete_queue_cloudify_utils.py", 
        "46_delete_queue_cloudify_workflows_workflow_context.py", 
        "46_delete_queue_agent_cloudify_agent_operations.py"
      ], 
      "patch_hash": "d48b8b24425a15013277af51d7928145506c239adb54ba56b9e66844e449fc89", 
      "patch_id": "46_delete_queue-d48b8b24425a15013277af51d7928145506c239adb54ba56b9e66844e449fc89", 
      "patch_name": "46_delete_queue", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_sync_replica.json", 
      "patch_description": "Use synchronous replication for 4.6 cluster.", 
      "patch_files": [
        "46_sync_replica_2_cloudify_premium_ha_checks.py", 
        "46_sync_replica_2_cloudify_premium_ha_database.py", 
        "46_sync_replica_2_cloudify_premium_ha_resources_postgresql.cluster.conf", 
        "46_sync_replica_2_cloudify_premium_ha_resources_sudo_trampoline.py", 
        "46_sync_replica_2_cloudify_premium_ha_handlers.py", 
        "46_sync_replica_2_cloudify_premium_ha_utils.py", 
        "46_sync_replica_2_cloudify_premium_ha_consul.py", 
        "46_sync_replica_2_cloudify_premium_ha_agents.py", 
        "46_sync_replica_2_cloudify_premium_ha_fix.py", 
        "46_sync_replica_2_cloudify_premium_ha_watch_handlers.py", 
        "46_mgmtworker_restart_packaging_mgmtworker_files_usr_lib_systemd_system_cloudify-mgmtworker.service"
      ], 
      "patch_hash": "01fd11e9ecb796b296349b879ce21ce46f36b02af29d275ba4e7ef1e848044dc", 
      "patch_id": "46_sync_replica-01fd11e9ecb796b296349b879ce21ce46f36b02af29d275ba4e7ef1e848044dc", 
      "patch_name": "46_sync_replica", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_restore_restore_admin_user_function.json", 
      "patch_description": "retoring the function _restore_admin_user.", 
      "patch_files": [
        "4_6_restore_restore_admin_user_function_workflows_cloudify_system_workflows_snapshots_snapshot_restore.py"
      ], 
      "patch_hash": "7017f1bbe51640d2b57be4945383d31810a6f97d95f6dc622717389dc1004926", 
      "patch_id": "4_6_restore_restore_admin_user_function-7017f1bbe51640d2b57be4945383d31810a6f97d95f6dc622717389dc1004926", 
      "patch_name": "4_6_restore_restore_admin_user_function", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_watch_lock.json", 
      "patch_description": "Make watch handlers only acquire locks when necessary.", 
      "patch_files": [
        "46_watch_lock_cloudify_premium_ha_watch_handlers.py"
      ], 
      "patch_hash": "4a496dfea24bf41c1b31ecdf6e212118cf8525b20b4bbbf1fa2967a608b3e35a", 
      "patch_id": "46_watch_lock-4a496dfea24bf41c1b31ecdf6e212118cf8525b20b4bbbf1fa2967a608b3e35a", 
      "patch_name": "46_watch_lock", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_amqp_db_write.json", 
      "patch_description": "Cluster: don't write to the db when replicating AMQP resources.", 
      "patch_files": [
        "46_amqp_db_write_rest-service_manager_rest_amqp_manager.py", 
        "46_amqp_db_write_premium_cloudify_premium_ha_commands.py"
      ], 
      "patch_hash": "fd80b8d289521242c7d51a6feb4c466f534673873b0f8088ea84a31450a66060", 
      "patch_id": "46_amqp_db_write-fd80b8d289521242c7d51a6feb4c466f534673873b0f8088ea84a31450a66060", 
      "patch_name": "46_amqp_db_write", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_hook_update_operation.json", 
      "patch_description": "Don't store operation state when running hooks.", 
      "patch_files": [
        "46_hook_update_operation_cloudify_dispatch.py"
      ], 
      "patch_hash": "8374066e943b306a2a4db66dfc3e5675f56467a04442fdde7f25fc9e7bcd9ad9", 
      "patch_id": "46_hook_update_operation-8374066e943b306a2a4db66dfc3e5675f56467a04442fdde7f25fc9e7bcd9ad9", 
      "patch_name": "46_hook_update_operation", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_agent_env_unicode.json", 
      "patch_description": "Don't break agent operations with unicode in env after a failover.", 
      "patch_files": [
        "46_agent_env_unicode_cloudify_workflows_workflow_context.py"
      ], 
      "patch_hash": "c186b0d8ed3709b8aa3c05aa7ee5f0428084646fc8107a1c1c635c77f534eb9f", 
      "patch_id": "46_agent_env_unicode-c186b0d8ed3709b8aa3c05aa7ee5f0428084646fc8107a1c1c635c77f534eb9f", 
      "patch_name": "46_agent_env_unicode", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_general_refactors_to_namespacing_process.json", 
      "patch_description": "Node templates relationships overloading support.", 
      "patch_files": [
        "4_6_general_refactors_to_namespacing_process_dsl_parser_utils.py", 
        "4_6_general_refactors_to_namespacing_process_dsl_parser_framework_parser.py", 
        "4_6_general_refactors_to_namespacing_process_dsl_parser_tests_abstract_test_parser.py", 
        "4_6_general_refactors_to_namespacing_process_dsl_parser_elements_imports.py", 
        "4_6_general_refactors_to_namespacing_process_dsl_parser_holder.py"
      ], 
      "patch_hash": "9ca57174441fd089a6b2ef37800e103f5362a53e725e36ec668c3725a47b9a42", 
      "patch_id": "4_6_general_refactors_to_namespacing_process-9ca57174441fd089a6b2ef37800e103f5362a53e725e36ec668c3725a47b9a42", 
      "patch_name": "4_6_general_refactors_to_namespacing_process", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_agent_install_after_failover.json", 
      "patch_description": "Fix agent install after manager failover.", 
      "patch_files": [
        "4_6_fix_agent_install_after_failover_cloudify_agent_installer_config_agent_config.py"
      ], 
      "patch_hash": "570a476d2f02e41a11f4d915a583cb80bf4a8a2baa48d59e099b769d60de8383", 
      "patch_id": "4_6_fix_agent_install_after_failover-570a476d2f02e41a11f4d915a583cb80bf4a8a2baa48d59e099b769d60de8383", 
      "patch_name": "4_6_fix_agent_install_after_failover", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_fix_integer_inputs_in_ui.json", 
      "patch_description": "Fixes handling Integer inputs in deployment creation in UI.", 
      "patch_files": [
        "4_6_fix_integer_inputs_in_ui_dist_appData_widgets_common_common.js", 
        "4_6_fix_integer_inputs_in_ui_dist_appData_widgets_common_common.js.br", 
        "4_6_fix_integer_inputs_in_ui_dist_appData_widgets_common_common.js.gz"
      ], 
      "patch_hash": "2baf782173a0938cc0f82ced1da5ccf6c13a6127cf492d223920ca8247ef9e47", 
      "patch_id": "4_6_fix_integer_inputs_in_ui-2baf782173a0938cc0f82ced1da5ccf6c13a6127cf492d223920ca8247ef9e47", 
      "patch_name": "4_6_fix_integer_inputs_in_ui", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_support_running_cloudify_proxy_client_on_py3.json", 
      "patch_description": "Support running cloudify proxy client on python3.", 
      "patch_files": [
        "46_support_running_cloudify_proxy_client_on_py3_cloudify_proxy_client.py"
      ], 
      "patch_hash": "6a65b63392ff703e39a0583d1b10cc01594f6faa9b49355bc74e770a731f5ca3", 
      "patch_id": "46_support_running_cloudify_proxy_client_on_py3-6a65b63392ff703e39a0583d1b10cc01594f6faa9b49355bc74e770a731f5ca3", 
      "patch_name": "46_support_running_cloudify_proxy_client_on_py3", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_events_truncate.json", 
      "patch_description": "Added options to delete events/logs for given deployment and specified period of time safely (i.e. with logs being stored prior to deletion).", 
      "patch_files": [
        "4_6_events_truncate_rest-service_manager_rest_rest_resources_v2_events.py", 
        "4_6_events_truncate_cloudify_cli_execution_events_fetcher.py", 
        "4_6_events_truncate_cloudify_cli_cli_helptexts.py", 
        "4_6_events_truncate_cloudify_cli_cli_cfy.py", 
        "4_6_events_truncate_cloudify_cli_commands_events.py"
      ], 
      "patch_hash": "05606b66334862d9961edfef90d453053c2a28c307a45aa160ba4b2a17cb2f83", 
      "patch_id": "4_6_events_truncate-05606b66334862d9961edfef90d453053c2a28c307a45aa160ba4b2a17cb2f83", 
      "patch_name": "4_6_events_truncate", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "46_syncthing_fs_watcher.json", 
      "patch_description": "Use FS watcher for syncthing.", 
      "patch_files": [
        "46_syncthing_fs_watcher_cloudify_premium_ha_syncthing.py"
      ], 
      "patch_hash": "87128def5371d388466a5d4e294a92ae1bc030b1308adfebaead9bca25cfb798", 
      "patch_id": "46_syncthing_fs_watcher-87128def5371d388466a5d4e294a92ae1bc030b1308adfebaead9bca25cfb798", 
      "patch_name": "46_syncthing_fs_watcher", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_store_pre_scale_state.json", 
      "patch_description": "Correctly store pre-scale state for rollbacks.", 
      "patch_files": [
        "4_6_store_pre_scale_state_rest-service_manager_rest_resource_manager.py"
      ], 
      "patch_hash": "0621c2d791beb8c8555cf46d05b44f910e51b18356116db34566892851929e55", 
      "patch_id": "4_6_store_pre_scale_state-0621c2d791beb8c8555cf46d05b44f910e51b18356116db34566892851929e55", 
      "patch_name": "4_6_store_pre_scale_state", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_unicode_in_logs.json", 
      "patch_description": "Allow Unicode in Cloudify logs.", 
      "patch_files": [
        "4_6_unicode_in_logs_cloudify_amqp_client.py", 
        "4_6_unicode_in_logs_cloudify_logs.py", 
        "4_6_unicode_in_logs_cloudify_event.py"
      ], 
      "patch_hash": "39623573db13df0ce0c42a4cf90f975e696d419a5dafafe52d958d711d0faf8f", 
      "patch_id": "4_6_unicode_in_logs-39623573db13df0ce0c42a4cf90f975e696d419a5dafafe52d958d711d0faf8f", 
      "patch_name": "4_6_unicode_in_logs", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_rollback_started_depmods.json", 
      "patch_description": "Rollback started dep-mods on scale_entity workflow.", 
      "patch_files": [
        "4_6_rollback_started_depmods_cloudify_workflows_workflow_context.py", 
        "4_6_rollback_started_depmods_cloudify_plugins_workflows.py"
      ], 
      "patch_hash": "07ac8a3f50f6dab45687c66ff5076f841ffd35125c168ad34dba2f603a40d42b", 
      "patch_id": "4_6_rollback_started_depmods-07ac8a3f50f6dab45687c66ff5076f841ffd35125c168ad34dba2f603a40d42b", 
      "patch_name": "4_6_rollback_started_depmods", 
      "supports_community": false
    }, 
    {
      "patch_definition_path": "4_6_unicode_in_task_runner.json", 
      "patch_description": "Allow Unicode in task runner.", 
      "patch_files": [
        "4_6_unicode_in_task_runner_script_runner_tasks.py", 
        "4_6_unicode_in_task_runner_cloudify_event.py"
      ], 
      "patch_hash": "b401cd356dc54f3081adbe8ab56a7016b0c2466e9ec9042263f888fd5c0bc1d0", 
      "patch_id": "4_6_unicode_in_task_runner-b401cd356dc54f3081adbe8ab56a7016b0c2466e9ec9042263f888fd5c0bc1d0", 
      "patch_name": "4_6_unicode_in_task_runner", 
      "supports_community": false
    }
  ]
}