{
    "affected_services": [
        "cloudify-mgmtworker",
        "cloudify-restservice"
    ],
    "community": false,
    "description": "Don't run retried tasks twice in resume with reset-operations.",
    "manager_versions": [
        "4.6"
    ],
    "patch_version": "2.0.0",
    "patches": [
        {
            "destinations": [
                "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks.py"
            ],
            "patch_file": "46_reset_operations_retry_cloudify_workflows_tasks.py",
            "sha256sum": "a638147f89be6945e136344809d58c8bbeb5465d4d9aad7b50eb44eff8bc1280"
        },
        {
            "destinations": [
                "/opt/manager/env/lib/python2.7/site-packages/manager_rest/resource_manager.py"
            ],
            "patch_file": "46_reset_operations_retry_manager_rest-service_manager_rest_resource_manager.py",
            "sha256sum": "781c9b4fca6e4c8a57f41a112f2719e44dbdace8d78aa2210a3266dfc88480ba"
        }
    ],
    "premium": true,
    "sha256sums_after": {
        "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks.py": [
            "47aeebe5bee681f3ed4281c07a1adef84e4baa99fa7d132dcacf8bb1bb493d87"
        ],
        "/opt/manager/env/lib/python2.7/site-packages/manager_rest/resource_manager.py": [
            "f5c5337540190011cd5c67ed5940509d930b760331626a5bf2484e2b02269112"
        ]
    },
    "sha256sums_before": {
        "/opt/mgmtworker/env/lib/python2.7/site-packages/cloudify/workflows/tasks.py": [
            "80e57b6267d28cb0a84558efd23bfad1fc0f5600b32f9086c0e5b907ec2b22fc"
        ],
        "/opt/manager/env/lib/python2.7/site-packages/manager_rest/resource_manager.py": [
            "fdf424f38e59f89ede50c45bf28c76cd037b5287c2d9c931bb119858c03706b8"
        ]
    }
}
